# Makefile
# aoneill - 02/27/17

all: calloc.o     \
     free.o       \
     malloc.o     \
     malloc_lmm.o \
     memalign.o   \
     realloc.o    \
     sfree.o      \
     smalloc.o    \
     smemalign.o

include $(MK_GENERIC)
