# Makefile
# aoneill - 02/27/17

all: lmm_add_free.o      \
     lmm_add_region.o    \
     lmm_alloc.o         \
     lmm_alloc_aligned.o \
     lmm_alloc_gen.o     \
     lmm_alloc_page.o    \
     lmm_avail.o         \
     lmm_dump.o          \
     lmm_find_free.o     \
     lmm_free.o          \
     lmm_free_page.o     \
     lmm_init.o          \
     lmm_remove_free.o

include $(MK_GENERIC)
