# Makefile
# aoneill - 02/27/17

all: bcopy.o \
	   memcmp.o     \
     memset.o     \
     rindex.o     \
     strcat.o     \
     strchr.o     \
     strcmp.o     \
     strcpy.o     \
     strcspn.o    \
     strdup.o     \
     strlen.o     \
     strncat.o    \
     strncmp.o    \
     strncpy.o    \
     strpbrk.o    \
     strrchr.o    \
     strspn.o     \
     strstr.o     \
     strtok.o

include $(MK_GENERIC)
